apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper-service
  template:
    metadata:
      labels:
        app: scraper-service
    spec:
      containers:
      - name: scraper-service
        image: muntashir/scraper_service:latest  # Replace with your image name
        ports:
        - containerPort: 8080
      securityContext:
        runAsUser: 1000           # Use the UID of appuser
        runAsGroup: 3000          # Set the group ID to a non-root group
        fsGroup: 3000